### ISSUE TITLE
Character missing on MacOS but not on Linux

### ISSUE THREAD

**Issue by cremacs** [flycheck/flycheck-pos-tip#29] opened 2019-02-11 18:40 UTC
Hi,

Using spacemacs with no extra configuration besides the syntax-checking layer, I get popups omitting the final character:

![image](https://user-images.githubusercontent.com/16630756/52585391-9b30f500-2e02-11e9-93c9-5df249922968.png)

This is using emacs-mac-port.

**Comment by fmdkdd** [comment] 2019-02-13 15:30
Weird!  This may come from `pos-tip` itself.   Could you try to call `(pos-tip-show "Expecting property name")`  and see how it behaves here?  Also, can you check the value of `flycheck-pos-tip-max-width`?

**Comment by cremacs** [comment] 2019-02-13 23:38
Calling `pos-tip-show` leads to a very quick flash of what looks to be an empty text box. The value of `flycheck-pos-tip-max-width` is `nil`.

I tried it out on the normal emacs for macOS (not the port), and I do get the all of the characters. I also get a different style tooltip, maybe that has something to do with it?

![image](https://user-images.githubusercontent.com/16630756/52751757-8d27d380-2fbe-11e9-9664-a87f5fced7e9.png)

**Comment by fmdkdd** [comment] 2019-02-14 10:19
> I tried it out on the normal emacs for macOS (not the port), and I do get all of the characters. I also get a different style tooltip, maybe that has something to do with it?

You may be onto something.  I suggest you try to ask the maintainers of the macOS port to see if the issue is on their side, or report that to the `pos-tip` maintainers.

From the look of it, it's not a Flycheck issue so I will close this.  Feel free to reopen if the diagnosis changes.

**Closed by fmdkdd** 2019-02-14 10:19 UTC
