### ISSUE TITLE
No themed pos tip any more

### ISSUE THREAD

**Issue by romanofski** [flycheck/flycheck-pos-tip#10] opened 2015-11-29 23:22 UTC
I'm using spacemacs and realised after the last few updates that my flycheck pos tip is not themed anymore:
![flycheck_error](https://cloud.githubusercontent.com/assets/121047/11460685/c164a934-973c-11e5-95c1-ce230b206eee.png)

Since it's just a black box, it can be sometimes annoying when it covers code underneath.

I've reported this issue to syl20bnr/spacemacs#3993 and was referred upstream. Details about my emacs setup:

My .emacs.d is currently at: 50ec30be6dd6be709a742dad51dfb016af1c37f0
My spacemacs config can be found here: https://github.com/romanofski/emacsrc/blob/master/spacemacs
Installed emacs is: emacs-24.5-6.fc23 (on Fedora 23)

I tried to use `customize-variable` to adjust the flycheck relevant bits towards pos-tip but no effect.

Thank you!

**Comment by stardiviner** [comment] 2015-11-30 04:57
I have this issue for a few days too. It's from library `showtip`. It can't be customized anymore. customization does not work.
You can test with `(showtip "test")`.

**Comment by stardiviner** [comment] 2015-11-30 05:08
@romanofski You can let `flycheck-pos-tip` use `popup` library. Might `flycheck-pos-tip` should provide an option of function to specify the popup library.

**Comment by lunaryorn** [comment] 2015-11-30 09:01
@romanofski I'm sorry, but that is by design.  This library shows error messages in a standard GUI tooltip, and thus has no control whatsoever over the appearance.  You'll notice that the tooltip looks exactly like tooltips from other Gnome applications.   

Unlike the previous popup.el-based approach tooltips work flawlessly without any visual glitches which popup.el is infamous for.  On the other side you can't customise the appearance anymore, and TTY support is gone.  As far as I'm concerned that's ok, but YMMV and I can understand that.

You can change the tooltip library by customising `flycheck-pos-tip-show-function` and `flycheck-pos-tip-hide-function`.  You can use these options to return to popup.el as @romanofski suggested.

However, this library will _not_ add support for popup.el again.  I think that popup.el is broken beyond repair.  It's infamous for display glitches and adverse interactions with other modes.   

I understand that it provides TTY support and plays better with custom themes, but it's also prone to bugs and that's simply not something I'd like to support in this library.

Sorry.  Closing as `wontfix`.

**Closed by lunaryorn** 2015-11-30 09:01 UTC

**Comment by stardiviner** [comment] 2015-11-30 09:55
@lunaryorn sorry to append comments on this closed issue.
But I want to know how to change this dark tooltip color?
Is it from GTK+ or other GUI library?
I'm using Plasma on Linux.

**Comment by lunaryorn** [comment] 2015-11-30 10:04
@stardiviner It's perfectly ok to add comments to a closed issue.  Closing issues does not stop discussion for me :relaxed:

I'm sorry but I can't answer your question.  I think it depends how Emacs is build.  On Linux it probably uses Gtk3 as GUI toolkit, so the tooltip is probably a Gtk3 tooltip, too.  However, there's also probably a package installed on your system that aligns the look of these tooltips with your KDE Plasma theme.  

But I'm really just guessing, and I have no idea how you could possible change the colour of the tooltip, if it's even possible at all.  I do not use Linux, and on OS X tooltips look very different.

**Comment by stardiviner** [comment] 2015-11-30 10:17
@lunaryorn Thanks for your help still.

**Comment by romanofski** [comment] 2015-12-01 00:06
@lunaryorn Thanks for explaining your reasoning behind the move to a different library. @stardiviner cheers for the additional help and work around.
